---
{
  apiVersion: "external-secrets.io/v1beta1",
  kind: "ExternalSecret",
  metadata: {
    name: "aid-secret",
    namespace: "{{ include `aid.namespace` . }}",
  },
  spec: {
    refreshInterval: "1m",
    secretStoreRef: {
      name: "vault-backend",
      kind: "ClusterSecretStore",
    },
    target: {
      name: "{{ .Values.secrets.target.name }}",
    },
    dataFrom: [{
      extract: {
          key: "{{ include `aid.namespace` . }}/aid/config",
      },
    }],
  },
}
